services:
  lb:
    image: nginx:alpine
    command: ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/stack/nginx.conf"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/stack:ro
    depends_on:
      - web1
      - web2
    networks:
      - edge

  web1:
    image: redmine:6-alpine
    env_file:
      - ./env/web1.env
    expose:
      - "3000"
    volumes:
      - web1_redmine_files:/usr/src/redmine/files
    depends_on:
      db:
        condition: service_healthy
    networks:
      edge:
      backend:

  web2:
    image: redmine:6-alpine
    env_file:
      - ./env/web2.env
    expose:
      - "3000"
    volumes:
      - web2_redmine_files:/usr/src/redmine/files
    depends_on:
      db:
        condition: service_healthy
    networks:
      edge:
      backend:

  dns:
    image: coredns/coredns:1.11.3
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
      - ./coredns/zones/hosts:/etc/coredns/zones/hosts:ro
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"

  db:
    image: postgres:16-alpine
    env_file:
      - ./env/db.env
    environment:
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine
    volumes:
      - redmine_pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redmine -d redmine"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  edge:
  backend:

volumes:
  redmine_pgdata:
  web1_redmine_files:
  web2_redmine_files:
