vault_postgres_password: localdev_pg_redmine_rotate_me
vault_redmine_secret_key_base: shared_rails_secret_for_two_redmine_nodes_rotate_me
vault_datadog_api_key: REPLACE_WITH_YOUR_DATADOG_API_KEY
vault_datadog_site: datadoghq.com
