pip_install_packages:
  - name: docker

redmine_port: 3000
redmine_domain: devops.example

postgres_password: "{{ vault_postgres_password }}"
redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"
